In [1]:
import pandas as pd
df=pd.read_csv('movie_blockbusters.csv')
df

,movie_id,title,year,decade,genre,runtime_min,budget_usd,revenue_usd,profit_usd,roi,rating,vote_count,popularity,blockbuster
0,1,Movie_0001,2020,2020s,Comedy,96,2.089233e+07,2.739209e+07,6.499763e+06,0.311,7.0,216326,9.64,0
1,2,Movie_0002,1981,1980s,Sci-Fi,128,3.063336e+08,1.237479e+09,9.311449e+08,3.040,5.3,49703,7.65,1
2,3,Movie_0003,1995,1990s,Horror,79,8.793950e+06,4.667246e+06,-4.126704e+06,-0.469,3.4,9476,16.68,0
3,4,Movie_0004,1988,1980s,Comedy,101,3.871710e+06,1.612737e+06,-2.258972e+06,-0.583,8.2,15698,2.93,0
4,5,Movie_0005,2023,2020s,Documentary,75,1.283539e+06,5.743469e+05,-7.091917e+05,-0.553,4.3,38698,9.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Movie_4996,2021,2020s,Comedy,71,2.548402e+07,5.560086e+07,3.011683e+07,1.182,7.4,181516,1.17,0
4996,4997,Movie_4997,2002,2000s,Comedy,75,9.045585e+07,4.017441e+07,-5.028144e+07,-0.556,4.4,14308,8.32,0
4997,4998,Movie_4998,1998,1990s,Documentary,79,7.906923e+05,2.595448e+05,-5.311475e+05,-0.672,6.4,13156,15.77,0
4998,4999,Movie_4999,2012,2010s,Documentary,98,8.636783e+06,1.480145e+07,6.164669e+06,0.714,5.7,340215,3.55,0
4999,5000,Movie_5000,2021,2020s,Comedy,71,2.534193e+06,2.238098e+06,-2.960951e+05,-0.117,8.2,10383,9.69,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     5000 non-null   int64
 1   title        5000 non-null   object
 2   year         5000 non-null   int64
 3   decade       5000 non-null   object
 4   genre        5000 non-null   object
 5   runtime_min  5000 non-null   int64
 6   budget_usd   5000 non-null   float64
 7   revenue_usd  5000 non-null   float64
 8   profit_usd   5000 non-null   float64
 9   roi          5000 non-null   float64
 10  rating       5000 non-null   float64
 11  vote_count   5000 non-null   int64
 12  popularity   5000 non-null   float64
 13  blockbuster  5000 non-null   int64
dtypes: float64(6), int64(5), object(3)
memory usage: 547.0+ KB

In [3]:
df.describe()

,movie_id,year,runtime_min,budget_usd,revenue_usd,profit_usd,roi,rating,vote_count,popularity,blockbuster
count,5000.000000,5000.000000,5000.000000,5.000000e+03,5.000000e+03,5.000000e+03,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.00000
mean,2500.500000,2002.200600,109.358000,4.320764e+07,1.311844e+08,8.797676e+07,1.517586,5.997220,6.932152e+04,20.002864,0.13460
std,1443.520003,12.956324,22.217699,9.897210e+07,5.012581e+08,4.485541e+08,3.233827,1.494474,3.210306e+05,26.695885,0.34133
min,1.000000,1980.000000,60.000000,1.054897e+05,1.403244e+04,-8.009002e+08,-0.980000,1.000000,8.700000e+01,0.370000,0.00000
25%,1250.750000,1991.000000,93.000000,5.072756e+06,5.707047e+06,-1.252205e+06,-0.258000,5.000000,7.866750e+03,6.330000,0.00000
50%,2500.500000,2002.000000,109.000000,1.501351e+07,2.327998e+07,5.049109e+06,0.506500,6.000000,2.181550e+04,12.195000,0.00000
75%,3750.250000,2013.000000,126.000000,4.191808e+07,8.887134e+07,4.406719e+07,2.029000,7.000000,5.766675e+04,23.585000,0.00000
max,5000.000000,2024.000000,185.000000,2.369801e+09,1.495518e+10,1.455845e+10,43.322000,10.000000,1.823086e+07,627.870000,1.00000

In [7]:
genre_budget=df.groupby('genre')['budget_usd'].mean().reset_index()

display(genre_budget)

         genre    budget_usd
0       Action  8.694937e+07
1    Adventure  8.330041e+07
2    Animation  5.800591e+07
3       Comedy  2.203204e+07
4  Documentary  5.099910e+06
5        Drama  2.044180e+07
6       Horror  1.230934e+07
7      Romance  1.836892e+07
8       Sci-Fi  9.942575e+07
9     Thriller  2.855104e+07

In [8]:
df.groupby('genre')['budget_usd'].sum()

genre
Action         4.243129e+10
Adventure      4.289971e+10
Animation      3.027909e+10
Comedy         1.099399e+10
Documentary    2.774351e+09
Drama          1.036399e+10
Horror         5.871556e+09
Romance        8.651762e+09
Sci-Fi         4.752551e+10
Thriller       1.424697e+10
Name: budget_usd, dtype: float64

In [ ]:
df.groupby('genre')['profit_usd'].mean().sort_values(ascending=False)

genre
Adventure      2.124380e+08
Action         2.054316e+08
Sci-Fi         1.789317e+08
Animation      1.745270e+08
Horror         4.149527e+07
Comedy         2.739505e+07
Thriller       2.391814e+07
Drama          1.243232e+07
Romance        6.122074e+06
Documentary   -1.819941e+06
Name: profit_usd, dtype: float64

In [13]:
df.groupby('genre')['profit_usd'].sum().sort_values(ascending=False)

genre
Adventure      1.094056e+11
Action         1.002506e+11
Animation      9.110311e+10
Sci-Fi         8.552936e+10
Horror         1.979324e+10
Comedy         1.367013e+10
Thriller       1.193515e+10
Drama          6.303185e+09
Romance        2.883497e+09
Documentary   -9.900478e+08
Name: profit_usd, dtype: float64

In [14]:
df.groupby(['decade', 'genre']).count()

                    movie_id  title  year  runtime_min  budget_usd  \
decade genre
1980s  Action            110    110   110          110         110
       Adventure         109    109   109          109         109
       Animation         112    112   112          112         112
       Comedy            112    112   112          112         112
       Documentary       125    125   125          125         125
       Drama             102    102   102          102         102
       Horror            117    117   117          117         117
       Romance           103    103   103          103         103
       Sci-Fi            108    108   108          108         108
       Thriller          108    108   108          108         108
1990s  Action             98     98    98           98          98
       Adventure         112    112   112          112         112
       Animation         135    135   135          135         135
       Comedy            105    105   105          105         105
       Documentary       118    118   118          118         118
       Drama             110    110   110          110         110
       Horror            101    101   101          101         101
       Romance           106    106   106          106         106
       Sci-Fi             93     93    93           93          93
       Thriller          103    103   103          103         103
2000s  Action             97     97    97           97          97
       Adventure         124    124   124          124         124
       Animation         100    100   100          100         100
       Comedy            127    127   127          127         127
       Documentary       121    121   121          121         121
       Drama             129    129   129          129         129
       Horror            101    101   101          101         101
       Romance           109    109   109          109         109
       Sci-Fi            109    109   109          109         109
       Thriller          131    131   131          131         131
2010s  Action            140    140   140          140         140
       Adventure         112    112   112          112         112
       Animation         110    110   110          110         110
       Comedy             94     94    94           94          94
       Documentary       119    119   119          119         119
       Drama             106    106   106          106         106
       Horror            103    103   103          103         103
       Romance            94     94    94           94          94
       Sci-Fi            104    104   104          104         104
       Thriller           97     97    97           97          97
2020s  Action             43     43    43           43          43
       Adventure          58     58    58           58          58
       Animation          65     65    65           65          65
       Comedy             61     61    61           61          61
       Documentary        61     61    61           61          61
       Drama              60     60    60           60          60
       Horror             55     55    55           55          55
       Romance            59     59    59           59          59
       Sci-Fi             64     64    64           64          64
       Thriller           60     60    60           60          60

                    revenue_usd  profit_usd  roi  rating  vote_count  \
decade genre
1980s  Action               110         110  110     110         110
       Adventure            109         109  109     109         109
       Animation            112         112  112     112         112
       Comedy               112         112  112     112         112
       Documentary          125         125  125     125         125
       Drama                102         102  102     102         102
       Horror               117         117  117     117         117
       Romance              103         103  103     103         103
       Sci-Fi               108         108  108     108         108
       Thriller             108         108  108     108         108
1990s  Action                98          98   98      98          98
       Adventure            112         112  112     112         112
       Animation            135         135  135     135         135
       Comedy               105         105  105     105         105
       Documentary          118         118  118     118         118
       Drama                110         110  110     110         110
       Horror               101         101  101     101         101
       Romance              106         106  106     106         106
       Sci-Fi                93          93   93      93          93
       Thriller             103         103  103     103         103
2000s  Action                97          97   97      97          97
       Adventure            124         124  124     124         124
       Animation            100         100  100     100         100
       Comedy               127         127  127     127         127
       Documentary          121         121  121     121         121
       Drama                129         129  129     129         129
       Horror               101         101  101     101         101
       Romance              109         109  109     109         109
       Sci-Fi               109         109  109     109         109
       Thriller             131         131  131     131         131
2010s  Action               140         140  140     140         140
       Adventure            112         112  112     112         112
       Animation            110         110  110     110         110
       Comedy                94          94   94      94          94
       Documentary          119         119  119     119         119
       Drama                106         106  106     106         106
       Horror               103         103  103     103         103
       Romance               94          94   94      94          94
       Sci-Fi               104         104  104     104         104
       Thriller              97          97   97      97          97
2020s  Action                43          43   43      43          43
       Adventure             58          58   58      58          58
       Animation             65          65   65      65          65
       Comedy                61          61   61      61          61
       Documentary           61          61   61      61          61
       Drama                 60          60   60      60          60
       Horror                55          55   55      55          55
       Romance               59          59   59      59          59
       Sci-Fi                64          64   64      64          64
       Thriller              60          60   60      60          60

                    popularity  blockbuster
decade genre
1980s  Action              110          110
       Adventure           109          109
       Animation           112          112
       Comedy              112          112
       Documentary         125          125
       Drama               102          102
       Horror              117          117
       Romance             103          103
       Sci-Fi              108          108
       Thriller            108          108
1990s  Action               98           98
       Adventure           112          112
       Animation           135          135
       Comedy              105          105
       Documentary         118          118
       Drama               110          110
       Horror              101          101
       Romance             106          106
       Sci-Fi               93           93
       Thriller            103          103
2000s  Action               97           97
       Adventure           124          124
       Animation           100          100
       Comedy              127          127
       Documentary         121          121
       Drama               129          129
       Horror              101          101
       Romance             109          109
       Sci-Fi              109          109
       Thriller            131          131
2010s  Action              140          140
       Adventure           112          112
       Animation           110          110
       Comedy               94           94
       Documentary         119          119
       Drama               106          106
       Horror              103          103
       Romance              94           94
       Sci-Fi              104          104
       Thriller             97           97
2020s  Action               43           43
       Adventure            58           58
       Animation            65           65
       Comedy               61           61
       Documentary          61           61
       Drama                60           60
       Horror               55           55
       Romance              59           59
       Sci-Fi               64           64
       Thriller             60           60

In [15]:
decgade_genre_count=df.groupby(['decade', 'genre'])['movie_id'].count().reset_index(name='total_movies')

display(decgade_genre_count)

   decade        genre  total_movies
0   1980s       Action           110
1   1980s    Adventure           109
2   1980s    Animation           112
3   1980s       Comedy           112
4   1980s  Documentary           125
5   1980s        Drama           102
6   1980s       Horror           117
7   1980s      Romance           103
8   1980s       Sci-Fi           108
9   1980s     Thriller           108
10  1990s       Action            98
11  1990s    Adventure           112
12  1990s    Animation           135
13  1990s       Comedy           105
14  1990s  Documentary           118
15  1990s        Drama           110
16  1990s       Horror           101
17  1990s      Romance           106
18  1990s       Sci-Fi            93
19  1990s     Thriller           103
20  2000s       Action            97
21  2000s    Adventure           124
22  2000s    Animation           100
23  2000s       Comedy           127
24  2000s  Documentary           121
25  2000s        Drama           129
26  2000s       Horror           101
27  2000s      Romance           109
28  2000s       Sci-Fi           109
29  2000s     Thriller           131
30  2010s       Action           140
31  2010s    Adventure           112
32  2010s    Animation           110
33  2010s       Comedy            94
34  2010s  Documentary           119
35  2010s        Drama           106
36  2010s       Horror           103
37  2010s      Romance            94
38  2010s       Sci-Fi           104
39  2010s     Thriller            97
40  2020s       Action            43
41  2020s    Adventure            58
42  2020s    Animation            65
43  2020s       Comedy            61
44  2020s  Documentary            61
45  2020s        Drama            60
46  2020s       Horror            55
47  2020s      Romance            59
48  2020s       Sci-Fi            64
49  2020s     Thriller            60

In [17]:
filtered_movies=df[(df['year']>2000) & (df['rating']>8.0)]

display(filtered_movies[['title', 'year', 'rating', 'genre']].head())

         title  year  rating        genre
41  Movie_0042  2004     8.6       Sci-Fi
62  Movie_0063  2023     9.2     Thriller
69  Movie_0070  2023     8.3  Documentary
72  Movie_0073  2007     8.3        Drama
81  Movie_0082  2013     8.5       Action

In [19]:
df[df['rating']>8.0].count()

movie_id       430
title          430
year           430
decade         430
genre          430
runtime_min    430
budget_usd     430
revenue_usd    430
profit_usd     430
roi            430
rating         430
vote_count     430
popularity     430
blockbuster    430
dtype: int64

In [23]:
df[df['rating']>9.0]

,movie_id,title,year,decade,genre,runtime_min,budget_usd,revenue_usd,profit_usd,roi,rating,vote_count,popularity,blockbuster
47,48,Movie_0048,1984,1980s,Horror,92,4.412072e+07,4.300657e+07,-1.114149e+06,-0.025,9.2,1178,21.94,0
62,63,Movie_0063,2023,2020s,Thriller,123,8.443752e+07,2.432270e+08,1.587895e+08,1.881,9.2,6967,14.63,0
102,103,Movie_0103,1984,1980s,Romance,106,1.150538e+07,3.947964e+06,-7.557420e+06,-0.657,9.7,26737,25.17,0
230,231,Movie_0231,2005,2000s,Documentary,96,5.564411e+06,1.452517e+06,-4.111893e+06,-0.739,9.2,8878,16.43,0
249,250,Movie_0250,1999,1990s,Documentary,100,1.569610e+07,3.866453e+07,2.296844e+07,1.463,9.1,134935,22.03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4864,4865,Movie_4865,2019,2010s,Thriller,103,2.410561e+07,2.254847e+07,-1.557140e+06,-0.065,9.6,76484,13.25,0
4928,4929,Movie_4929,1981,1980s,Horror,94,3.166545e+06,2.143140e+07,1.826485e+07,5.768,9.8,117513,42.93,0
4948,4949,Movie_4949,2004,2000s,Romance,82,4.139338e+05,5.947177e+05,1.807839e+05,0.437,9.2,12526,23.98,0
4961,4962,Movie_4962,1984,1980s,Drama,113,4.849043e+07,1.290106e+08,8.052015e+07,1.661,9.8,17682,28.80,0
4992,4993,Movie_4993,2004,2000s,Action,151,1.586402e+08,6.545052e+07,-9.318964e+07,-0.587,9.7,5830,11.37,0